name: Notion Board
on:
  issues:
  issue_comment:
  workflow_dispatch:
jobs:
  notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notion Board
        uses: Souvikns/Notion-Board@latest
        env: 
          GITHUB_TOKEN: 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
          NOTION_API_KEY: secret_LiDDIMsEPHx7HZOkQbJ9ublGeeFY32PLzq8wXACtFye
          NOTION_DATABASE: 3aac3868d4b94d38be48a3d7e6009bc5
