name: Notion Sync

on:
  workflow_dispatch:
  issues:
    types:
      [
        opened,
        edited,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        milestoned,
        demilestoned,
        reopened,
        closed,
      ]

jobs:
  notion_job:
    runs-on: ubuntu-latest
    name: Add GitHub Issues to Notion
    steps:
      - name: Add GitHub Issues to Notion
        uses: Hwangsooneun/notion-github-action@v1.2.0
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-db: 3aac3868d4b94d38be48a3d7e6009bc5
